//! Ancestry-informative-marker (AIM) panel: 1000 Genomes phase 3
//! super-population effect-allele frequencies (Ensembl REST) plus GRCh37 /
//! GRCh38 positions. Generated by `scripts/gen_aim_panel.py`; do not edit by
//! hand. Frequencies are build-independent; positions are per build.

/// One ancestry-informative marker.
pub struct Aim {
    pub rsid: &'static str,
    pub contig: &'static str,
    pub pos37: u32,
    pub pos38: u32,
    /// Effect allele (the one `freq` is the frequency of), as an ASCII base.
    pub effect: u8,
    /// Effect-allele frequency per super-population, in SUPERPOPS order.
    pub freq: [f64; 5],
}

/// Super-population labels, the index order of `Aim::freq` and estimates.
pub const SUPERPOPS: [&str; 5] = ["AFR", "AMR", "EAS", "EUR", "SAS"];

/// Human-readable super-population names (same order as SUPERPOPS).
pub const SUPERPOP_NAMES: [&str; 5] = [
    "African", "Admixed American", "East Asian", "European", "South Asian",
];

// Frequencies are data; some coincidentally approximate math constants.
#[allow(clippy::approx_constant)]
#[rustfmt::skip]
pub const PANEL: &[Aim] = &[
    Aim { rsid: "rs3737576", contig: "1", pos37: 101709563, pos38: 101244007, effect: b'C', freq: [0.0166, 0.3256, 0.0804, 0.0527, 0.0399] },
    Aim { rsid: "rs7554936", contig: "1", pos37: 151122489, pos38: 151150013, effect: b'C', freq: [0.9697, 0.3199, 0.1438, 0.334, 0.2188] },
    Aim { rsid: "rs2814778", contig: "1", pos37: 159174683, pos38: 159204893, effect: b'C', freq: [0.9637, 0.0778, 0.0, 0.006, 0.0] },
    Aim { rsid: "rs1407434", contig: "1", pos37: 186149032, pos38: 186179900, effect: b'A', freq: [0.2421, 0.3617, 0.4812, 0.0994, 0.229] },
    Aim { rsid: "rs798443", contig: "2", pos37: 7968275, pos38: 7828144, effect: b'A', freq: [0.0628, 0.6744, 0.6329, 0.8191, 0.6687] },
    Aim { rsid: "rs7421394", contig: "2", pos37: 14756349, pos38: 14616225, effect: b'A', freq: [0.0545, 0.5144, 0.5208, 0.7097, 0.5307] },
    Aim { rsid: "rs1876482", contig: "2", pos37: 17362568, pos38: 17181301, effect: b'A', freq: [0.0023, 0.2305, 0.7748, 0.0775, 0.2249] },
    Aim { rsid: "rs3827760", contig: "2", pos37: 109513601, pos38: 108897145, effect: b'A', freq: [0.997, 0.6081, 0.127, 0.9891, 0.9867] },
    Aim { rsid: "rs260690", contig: "2", pos37: 109579738, pos38: 108963282, effect: b'A', freq: [0.3707, 0.536, 0.0635, 0.9225, 0.8865] },
    Aim { rsid: "rs6754311", contig: "2", pos37: 136707982, pos38: 135950412, effect: b'C', freq: [0.9743, 0.7781, 1.0, 0.4891, 0.8783] },
    Aim { rsid: "rs4954681", contig: "2", pos37: 141724469, pos38: 140966900, effect: b'A', freq: [0.6316, 0.8141, 0.7371, 0.8738, 0.7689] },
    Aim { rsid: "rs10497191", contig: "2", pos37: 158667217, pos38: 157810705, effect: b'C', freq: [0.0779, 0.8141, 0.9038, 0.8767, 0.9029] },
    Aim { rsid: "rs6437783", contig: "3", pos37: 108172817, pos38: 108453970, effect: b'C', freq: [0.2791, 0.3818, 0.9821, 0.173, 0.4305] },
    Aim { rsid: "rs12498138", contig: "3", pos37: 121459589, pos38: 121740742, effect: b'A', freq: [0.0068, 0.3617, 0.0843, 0.0696, 0.0368] },
    Aim { rsid: "rs4833103", contig: "4", pos37: 38815502, pos38: 38813881, effect: b'A', freq: [0.0182, 0.2075, 0.0, 0.505, 0.0143] },
    Aim { rsid: "rs10007810", contig: "4", pos37: 41554364, pos38: 41552347, effect: b'A', freq: [0.9554, 0.2565, 0.1131, 0.2058, 0.4499] },
    Aim { rsid: "rs1229984", contig: "4", pos37: 100239319, pos38: 99318162, effect: b'C', freq: [0.9985, 0.9424, 0.3026, 0.9712, 0.9796] },
    Aim { rsid: "rs3811801", contig: "4", pos37: 100244319, pos38: 99323162, effect: b'A', freq: [0.0, 0.0, 0.5099, 0.0, 0.0] },
    Aim { rsid: "rs7657799", contig: "4", pos37: 105375423, pos38: 104454266, effect: b'G', freq: [0.7943, 0.0562, 0.1637, 0.0219, 0.0695] },
    Aim { rsid: "rs16891982", contig: "5", pos37: 33951693, pos38: 33951588, effect: b'C', freq: [0.9644, 0.536, 0.994, 0.0616, 0.9407] },
    Aim { rsid: "rs7745461", contig: "6", pos37: 21911616, pos38: 21911385, effect: b'A', freq: [0.3457, 0.3501, 0.7411, 0.1213, 0.3037] },
    Aim { rsid: "rs192655", contig: "6", pos37: 90518278, pos38: 89808559, effect: b'A', freq: [0.6014, 0.6124, 0.3294, 0.9145, 0.7515] },
    Aim { rsid: "rs3823159", contig: "6", pos37: 136482727, pos38: 136161589, effect: b'A', freq: [0.1452, 0.7334, 0.8899, 0.9801, 0.9335] },
    Aim { rsid: "rs10108270", contig: "8", pos37: 4190793, pos38: 4333271, effect: b'A', freq: [0.9062, 0.245, 0.3442, 0.2982, 0.4796] },
    Aim { rsid: "rs6990312", contig: "8", pos37: 110602317, pos38: 109590088, effect: b'G', freq: [0.3056, 0.7248, 0.9831, 0.8559, 0.6718] },
    Aim { rsid: "rs2196051", contig: "8", pos37: 122124302, pos38: 121112062, effect: b'A', freq: [0.0325, 0.3674, 0.001, 0.7048, 0.1892] },
    Aim { rsid: "rs3814134", contig: "9", pos37: 127267689, pos38: 124505410, effect: b'A', freq: [0.1672, 0.9107, 0.6875, 0.9781, 0.8773] },
    Aim { rsid: "rs4918664", contig: "10", pos37: 94921065, pos38: 93161308, effect: b'A', freq: [0.9811, 0.6037, 0.1349, 0.8767, 0.6074] },
    Aim { rsid: "rs174570", contig: "11", pos37: 61597212, pos38: 61829740, effect: b'C', freq: [0.9909, 0.513, 0.4444, 0.84, 0.9264] },
    Aim { rsid: "rs1042602", contig: "11", pos37: 88911696, pos38: 89178528, effect: b'A', freq: [0.0121, 0.2378, 0.001, 0.3718, 0.0634] },
    Aim { rsid: "rs1079597", contig: "11", pos37: 113296286, pos38: 113425564, effect: b'C', freq: [0.8343, 0.7291, 0.5863, 0.8509, 0.7117] },
    Aim { rsid: "rs772262", contig: "12", pos37: 56163734, pos38: 55769950, effect: b'A', freq: [0.8003, 0.3055, 0.1597, 0.0905, 0.1472] },
    Aim { rsid: "rs2070586", contig: "12", pos37: 109277720, pos38: 108883944, effect: b'A', freq: [0.3926, 0.451, 0.3194, 0.1809, 0.1892] },
    Aim { rsid: "rs2238151", contig: "12", pos37: 112211833, pos38: 111774029, effect: b'C', freq: [0.966, 0.4207, 0.9315, 0.3131, 0.6912] },
    Aim { rsid: "rs671", contig: "12", pos37: 112241766, pos38: 111803962, effect: b'A', freq: [0.0015, 0.0029, 0.1736, 0.0, 0.0] },
    Aim { rsid: "rs7997709", contig: "13", pos37: 34847737, pos38: 34273600, effect: b'C', freq: [0.2103, 0.4121, 0.6915, 0.0557, 0.2188] },
    Aim { rsid: "rs1572018", contig: "13", pos37: 41715282, pos38: 41141146, effect: b'C', freq: [0.0635, 0.8098, 0.3512, 0.832, 0.6708] },
    Aim { rsid: "rs2166624", contig: "13", pos37: 42579985, pos38: 42005849, effect: b'A', freq: [0.0182, 0.5778, 0.3968, 0.3738, 0.3446] },
    Aim { rsid: "rs9522149", contig: "13", pos37: 111827167, pos38: 111174820, effect: b'C', freq: [0.0567, 0.4294, 0.0119, 0.7634, 0.2127] },
    Aim { rsid: "rs2402130", contig: "14", pos37: 92801203, pos38: 92334859, effect: b'A', freq: [0.4002, 0.7925, 0.9395, 0.7873, 0.862] },
    Aim { rsid: "rs200354", contig: "14", pos37: 99375321, pos38: 98908984, effect: b'G', freq: [0.3359, 0.4755, 0.251, 0.829, 0.635] },
    Aim { rsid: "rs1800414", contig: "15", pos37: 28197037, pos38: 27951891, effect: b'C', freq: [0.0008, 0.0, 0.5962, 0.0, 0.0041] },
    Aim { rsid: "rs1800407", contig: "15", pos37: 28230318, pos38: 27985172, effect: b'C', freq: [0.9985, 0.9683, 0.999, 0.9245, 0.9734] },
    Aim { rsid: "rs12913832", contig: "15", pos37: 28365618, pos38: 28120472, effect: b'A', freq: [0.972, 0.7983, 0.998, 0.3638, 0.9294] },
    Aim { rsid: "rs12439433", contig: "15", pos37: 36220035, pos38: 35927834, effect: b'A', freq: [0.9962, 0.8012, 0.995, 0.9563, 0.9898] },
    Aim { rsid: "rs735480", contig: "15", pos37: 45152371, pos38: 44860173, effect: b'C', freq: [0.9486, 0.3674, 0.4137, 0.1074, 0.229] },
    Aim { rsid: "rs1834640", contig: "15", pos37: 48392165, pos38: 48099968, effect: b'A', freq: [0.0734, 0.6859, 0.0764, 0.994, 0.6851] },
    Aim { rsid: "rs1426654", contig: "15", pos37: 48426484, pos38: 48134287, effect: b'A', freq: [0.0741, 0.5893, 0.0119, 0.997, 0.6851] },
    Aim { rsid: "rs459920", contig: "16", pos37: 89730827, pos38: 89664419, effect: b'C', freq: [0.171, 0.3329, 0.0159, 0.4771, 0.1871] },
    Aim { rsid: "rs4411548", contig: "17", pos37: 40658533, pos38: 42506515, effect: b'C', freq: [0.8101, 0.7233, 0.9821, 0.7425, 0.8497] },
    Aim { rsid: "rs4471745", contig: "17", pos37: 53568884, pos38: 55491523, effect: b'A', freq: [0.0552, 0.0375, 0.129, 0.0547, 0.0951] },
    Aim { rsid: "rs2125345", contig: "17", pos37: 73782191, pos38: 75786110, effect: b'C', freq: [0.9539, 0.3343, 0.498, 0.3121, 0.3497] },
    Aim { rsid: "rs7226659", contig: "18", pos37: 40488279, pos38: 42908314, effect: b'G', freq: [0.9713, 0.8127, 0.3958, 0.9692, 0.8589] },
    Aim { rsid: "rs1369290", contig: "18", pos37: 67691520, pos38: 70024284, effect: b'A', freq: [0.8631, 0.0922, 0.004, 0.0398, 0.0695] },
    Aim { rsid: "rs6058017", contig: "20", pos37: 32856998, pos38: 34269192, effect: b'A', freq: [0.2088, 0.8646, 0.7877, 0.8966, 0.8333] },
    Aim { rsid: "rs2378249", contig: "20", pos37: 33218090, pos38: 34630286, effect: b'A', freq: [0.8434, 0.9395, 0.8224, 0.8827, 0.6176] },
];
