[package]
name = "gx-plasmid"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
gx-core = { version = "0.1.0", path = "../gx-core" }
serde = { version = "1.0.228", features = ["derive"] }

[lints]
workspace = true
